runtime: custom
env: flex

env_variables:
  NODE_ENV: "production"
  PORT: "8080"

automatic_scaling:
  min_instances: 1
  max_instances: 3

readiness_check:
  path: "/healthz"
  timeout_sec: 30
  check_interval_sec: 5

liveness_check:
  path: "/healthz"
  timeout_sec: 30
  check_interval_sec: 5
