import { db } from "@workspace/db";
import { peopleTable, sourcesTable, communitiesTable } from "@workspace/db/schema";
import { logger } from "./logger";

const people = [
  { name: "Geoffrey Hinton", role: "AI Pioneer, Former VP & Fellow at Google", organization: "University of Toronto", category: "godfathers", bio: "Co-creator of backpropagation and deep neural networks. Shared the 2018 Turing Award. Left Google in 2023 to speak freely about AI risks.", stance: "Existential risk alarm — believes AI poses genuine existential dangers to humanity", twitterHandle: "geoffreyhinton", twitterFollowers: "700K+", primaryPlatform: "X + LinkedIn", bestFor: "Understanding the deep roots of neural networks and the most serious safety concerns from someone who built the foundations", isSpotlight: true },
  { name: "Yann LeCun", role: "Chief AI Scientist at Meta", organization: "Meta / NYU", category: "godfathers", bio: "Creator of convolutional neural networks (CNNs), the backbone of all computer vision. Turing Award winner 2018. Highly active and combative debater on X.", stance: "Contrarian — argues current LLMs are fundamentally limited and not on the path to AGI", twitterHandle: "ylecun", twitterFollowers: "972K", primaryPlatform: "X", bestFor: "Alternative view on LLM limitations; deep expertise in vision and architecture design", isSpotlight: false },
  { name: "Yoshua Bengio", role: "Scientific Director at MILA", organization: "MILA / Université de Montréal", category: "godfathers", bio: "Solved the vanishing gradient problem. Founded MILA, the world's top AI research institute. Writes long-form safety essays on LinkedIn.", stance: "Safety-focused, measured, and deeply concerned about misaligned AI", twitterHandle: "yoshuabengio", twitterFollowers: "200K+", primaryPlatform: "LinkedIn", bestFor: "Deep, nuanced perspective on AI safety from one of the field's most credible voices", isSpotlight: false },
  { name: "Fei-Fei Li", role: "Co-Director, Stanford HAI", organization: "Stanford University", category: "godfathers", bio: "Created ImageNet — the dataset that triggered the deep learning explosion. Runs Stanford's Human-Centered AI Institute.", stance: "Human-centered AI; champions diversity, inclusion, and responsible deployment", twitterHandle: "drfeifei", twitterFollowers: "350K+", primaryPlatform: "X + LinkedIn", bestFor: "Human-centered AI perspective; responsible deployment of powerful systems", isSpotlight: false },
  { name: "Andrew Ng", role: "Founder, DeepLearning.AI & AI Fund", organization: "DeepLearning.AI", category: "godfathers", bio: "Co-founded Google Brain and Coursera. Built Baidu's AI division. Writes The Batch newsletter weekly. Best bridge between research and practice.", stance: "Optimistic pragmatist — focuses on AI democratization and practical deployment", twitterHandle: "AndrewYNg", twitterFollowers: "800K+", primaryPlatform: "X + LinkedIn", bestFor: "Bridging AI research and real-world application; weekly signal in The Batch", isSpotlight: false },
  { name: "Sam Altman", role: "CEO, OpenAI", organization: "OpenAI", category: "lab_ceos", bio: "#1 on AI Magazine's Top 100 AI Leaders 2026. Led GPT-4, GPT-5 launches and $40B funding round at $300B valuation.", stance: "Cautiously optimistic — advocates for responsible development while racing toward AGI", twitterHandle: "sama", twitterFollowers: "3M+", primaryPlatform: "X", bestFor: "First-hand view of OpenAI's direction; candid takes on frontier AI development", isSpotlight: false },
  { name: "Dario Amodei", role: "CEO, Anthropic", organization: "Anthropic", category: "lab_ceos", bio: "Safety-first alternative to OpenAI. Raised $27.3B. Thoughtful long-form blogger. Shapes Claude's Constitutional AI direction.", stance: "Safety-first — methodical, research-driven, deeply concerned about alignment", twitterHandle: "darioamodei", twitterFollowers: "200K+", primaryPlatform: "Blog + X", bestFor: "Safety-focused perspective on frontier AI; understanding how Anthropic thinks about alignment", isSpotlight: false },
  { name: "Demis Hassabis", role: "CEO, Google DeepMind", organization: "Google DeepMind", category: "lab_ceos", bio: "2024 Nobel Prize in Chemistry for AlphaFold. Knighted in 2024. Leads 6,000-person team toward AGI. Co-founded DeepMind in 2010.", stance: "Scientific optimism — believes AGI is achievable and will be profoundly beneficial", twitterHandle: "demishassabis", twitterFollowers: "500K+", primaryPlatform: "X", bestFor: "Scientific AI research perspective; DeepMind's moonshot approach to AGI", isSpotlight: false },
  { name: "Ilya Sutskever", role: "CEO, Safe Superintelligence", organization: "Safe Superintelligence (SSI)", category: "lab_ceos", bio: "Co-created AlexNet, co-founded OpenAI. Left to build SSI — focused purely on safe superintelligence without commercial pressure.", stance: "Safety absolutist — left OpenAI specifically to focus on superintelligence safety without distraction", twitterHandle: "ilyasut", twitterFollowers: "400K+", primaryPlatform: "X", bestFor: "Understanding the most safety-focused frontier lab; what safety-first AGI development looks like", isSpotlight: false },
  { name: "Jensen Huang", role: "CEO, NVIDIA", organization: "NVIDIA", category: "hardware", bio: "#2 on AI Magazine Top 100. Without NVIDIA's GPUs the current AI wave doesn't exist. His keynotes are industry state-of-the-union addresses.", stance: "Bullish on AI's transformative power; believes we are at an inflection point in computing history", twitterHandle: "nvidia", twitterFollowers: "10M+ (NVIDIA)", primaryPlatform: "LinkedIn + Keynotes", bestFor: "Hardware supply chain; understanding what compute constraints mean for AI development pace", isSpotlight: false },
  { name: "Lisa Su", role: "CEO, AMD", organization: "AMD", category: "hardware", bio: "#10 on AI Magazine Top 100. Main challenger to NVIDIA's AI chip dominance. Leading AMD's aggressive push into AI accelerators.", stance: "Competitive optimist — AMD can challenge NVIDIA's dominance in AI compute", twitterHandle: "lisasu", twitterFollowers: "100K+", primaryPlatform: "LinkedIn", bestFor: "Alternative to NVIDIA compute narrative; GPU market dynamics and AI chip competition", isSpotlight: false },
  { name: "Andrej Karpathy", role: "Founder, Eureka Labs", organization: "Eureka Labs", category: "builders", bio: "Coined 'vibe coding.' Ex-Tesla AI Director, ex-OpenAI. 1.3M followers on X. Produces the most trusted deep technical LLM explainers.", stance: "Enthusiastically optimistic — sees AI tools as fundamentally changing how software is built", twitterHandle: "karpathy", twitterFollowers: "1.3M", primaryPlatform: "X + YouTube", bestFor: "Deep technical LLM understanding; best bridge between research and engineering practice", isSpotlight: false },
  { name: "Simon Willison", role: "Creator of Datasette; Co-creator of Django", organization: "Independent", category: "builders", bio: "Writes simonwillison.net daily — 575+ posts tagged 'llm'. The most consistent practical LLM usage tracker on the internet.", stance: "Pragmatic explorer — focused on what actually works today, including security considerations", twitterHandle: "simonw", twitterFollowers: "200K+", primaryPlatform: "Blog", bestFor: "Daily practical LLM usage, tool-building, prompt injection risks — the 'what works today' source", isSpotlight: false },
  { name: "swyx (Shawn Wang)", role: "Co-host, Latent Space Podcast", organization: "Latent Space", category: "builders", bio: "Coined 'AI Engineer.' Latent Space is the #1 podcast for AI engineers with 176K+ subscribers. Deeply embedded in the AI engineering community.", stance: "Builder-first — focused on what practitioners need to build and ship AI products", twitterHandle: "swyx", twitterFollowers: "250K+", primaryPlatform: "X + Substack + Podcast", bestFor: "AI engineering culture and practice; what builders are actually shipping", isSpotlight: false },
  { name: "Gary Marcus", role: "Cognitive Scientist & AI Critic", organization: "NYU (Emeritus)", category: "builders", bio: "The most credible AI skeptic. Regularly challenges AI hype with rigorous arguments. Essential counterbalance in any balanced feed.", stance: "Critical realist — believes current AI systems are fundamentally brittle and AGI claims are premature", twitterHandle: "GaryMarcus", twitterFollowers: "197K", primaryPlatform: "X + Substack", bestFor: "Credible counterpoint to AI hype; understanding real limitations of current systems", isSpotlight: false },
  { name: "Lilian Weng", role: "Safety Researcher, OpenAI", organization: "OpenAI", category: "builders", bio: "Maintains one of the most respected technical AI blogs. Deep explainers on agents, RLHF, diffusion models. Monthly but extremely high depth.", stance: "Research-first — rigorous empirical approach to understanding AI systems", twitterHandle: "lilianweng", twitterFollowers: "150K+", primaryPlatform: "Blog", bestFor: "Deep technical explainers on agents, RLHF, prompting — graduate-level depth made accessible", isSpotlight: false },
  { name: "Dwarkesh Patel", role: "Podcaster", organization: "Dwarkesh Podcast", category: "builders", bio: "Called 'Silicon Valley's favourite podcaster' by The Economist. Dense, research-backed interviews with the most important AI figures.", stance: "Curious empiricist — uses dense research to draw out views that don't appear in press releases", twitterHandle: "dwarkesh_sp", twitterFollowers: "200K+", primaryPlatform: "Podcast + Substack", bestFor: "The deepest conversations in AI — Karpathy, Sutskever, Zuckerberg like you've never heard them", isSpotlight: false },
  { name: "Nate Liason", role: "Author & Vibe Coding Educator", organization: "Independent", category: "vibe_coders", bio: "75.8K followers on X. Teaches vibe coding workflows to non-technical builders. Focuses on practical no-code-adjacent AI building.", stance: null, twitterHandle: "nateliason", twitterFollowers: "75.8K", primaryPlatform: "X + Newsletter", bestFor: "Practical vibe coding workflows for non-technical builders", isSpotlight: false },
  { name: "Peter Steinberger", role: "Developer & Vibe Coder", organization: "Independent", category: "vibe_coders", bio: "41.4K followers on X. Bridges between vibe coding and serious agentic engineering. Shows what professionals can build with AI assistance.", stance: null, twitterHandle: "steipete", twitterFollowers: "41.4K", primaryPlatform: "X", bestFor: "Professional-grade vibe coding; what serious engineers can ship with AI tools", isSpotlight: false },
  { name: "Matt Palmer", role: "Vibe Coding Lead at Replit", organization: "Replit", category: "vibe_coders", bio: "28.2K followers on X. Works on vibe coding product at Replit — inside view on the tools powering the movement.", stance: null, twitterHandle: "mattppal", twitterFollowers: "28.2K", primaryPlatform: "X", bestFor: "Inside view on vibe coding tooling; what Replit is building for AI-assisted development", isSpotlight: false },
  { name: "Aravind Srinivas", role: "CEO, Perplexity AI", organization: "Perplexity AI", category: "lab_ceos", bio: "Built Perplexity into a search-disrupting AI company valued at $14B. Former researcher at OpenAI and Google DeepMind. Launched Perplexity Computer as a safer alternative to AI computer-use tools.", stance: "Pragmatic optimist — believes AI can fundamentally reimagine how we access and synthesize information", twitterHandle: "AravSrinivas", twitterFollowers: "300K+", primaryPlatform: "X + LinkedIn", bestFor: "AI search, information retrieval, and the future of how we access knowledge", isSpotlight: false },
  { name: "Guillermo Rauch", role: "CEO, Vercel", organization: "Vercel", category: "builders", bio: "Creator of Next.js — the framework powering a huge share of the AI-era web. Forbes profile March 2026. Building the infrastructure layer for AI-generated frontends.", stance: "Infrastructure optimist — AI dramatically lowers the floor for web creation", twitterHandle: "rauchg", twitterFollowers: "500K+", primaryPlatform: "X", bestFor: "AI-era web development and frontend infrastructure; where web tooling is heading next", isSpotlight: false },
  { name: "Ethan Mollick", role: "Professor, Wharton; Author of Co-Intelligence", organization: "Wharton School, UPenn", category: "builders", bio: "Writes One Useful Thing — the most practical AI learning resource for knowledge workers. Author of Co-Intelligence. Runs real experiments on how AI changes work, education, and creativity.", stance: "Evidence-based optimist — rigorously tests what AI can and cannot do rather than speculating", twitterHandle: "emollick", twitterFollowers: "600K+", primaryPlatform: "Substack + X", bestFor: "How AI changes knowledge work and education — backed by real experiments, not hype", isSpotlight: false },
  { name: "Sigrid Jin", role: "Developer & World's Most Active Claude Code User", organization: "Independent", category: "vibe_coders", bio: "Reported by WSJ to have personally used 25 billion Claude tokens in a year. When Anthropic accidentally leaked their source code via npm, he rewrote the entire thing in Python from scratch before sunrise — the resulting 'claw-code' repo hit 30,000 GitHub stars faster than any repo in history.", stance: null, twitterHandle: "sigridjin", twitterFollowers: "50K+", primaryPlatform: "GitHub + X", bestFor: "What's possible at the absolute frontier of AI-assisted engineering; living proof of AI's productivity multiplier", isSpotlight: false },
];

const sources = [
  { name: "The Rundown AI", type: "newsletter", description: "Daily AI news digest covering model releases, research breakthroughs, and industry moves", audience: "Founders, C-suite executives", frequency: "Daily", url: "https://therundown.ai", subscriberCount: "1.75M+", host: null, bestFor: "Executive-level daily AI briefing", isHighSignal: true },
  { name: "TLDR AI", type: "newsletter", description: "Curated daily AI newsletter for technical readers", audience: "Engineers, data scientists", frequency: "Daily", url: "https://tldr.tech/ai", subscriberCount: "1.25M+", host: null, bestFor: "Technical daily digest — fast to read, high signal", isHighSignal: true },
  { name: "The Batch", type: "newsletter", description: "Andrew Ng's weekly newsletter bridging AI research and business application", audience: "Mixed technical and business", frequency: "Weekly", url: "https://deeplearning.ai/the-batch", subscriberCount: "500K+", host: "Andrew Ng", bestFor: "Research-to-practice bridge; best weekly for understanding what research means for builders", isHighSignal: true },
  { name: "Ben's Bites", type: "newsletter", description: "Daily curation of AI tools, products, and news for builders", audience: "Builders, product people", frequency: "Daily", url: "https://bensbites.co", subscriberCount: "100K+", host: "Ben Tossell", bestFor: "New AI tools and product launches — essential for staying on top of the tooling landscape", isHighSignal: true },
  { name: "Latent Space", type: "newsletter", description: "Newsletter and podcast for AI engineers — technical depth on what's being built", audience: "AI engineers", frequency: "Weekly", url: "https://latent.space", subscriberCount: "176K+", host: "swyx & Alessio", bestFor: "AI engineering depth — what practitioners are actually building", isHighSignal: true },
  { name: "Import AI", type: "newsletter", description: "Jack Clark's weekly deep-dive on frontier research, AI risks, and global policy", audience: "Technical leaders and researchers", frequency: "Weekly", url: "https://jack-clark.net", subscriberCount: "50K+", host: "Jack Clark", bestFor: "Frontier research and AI policy — what's happening in the labs and governments", isHighSignal: true },
  { name: "Ahead of AI", type: "newsletter", description: "Sebastian Raschka's hands-on LLM tutorials with real code", audience: "ML practitioners", frequency: "Weekly", url: "https://magazine.sebastianraschka.com", subscriberCount: "50K+", host: "Sebastian Raschka", bestFor: "Hands-on LLM implementation — readable code, not just theory", isHighSignal: false },
  { name: "Simon Willison's Weblog", type: "blog", description: "Daily practical notes on LLMs, tools, and prompt injection. Over 575 posts tagged 'llm'", audience: "Developers and engineers", frequency: "Daily", url: "https://simonwillison.net", subscriberCount: null, host: "Simon Willison", bestFor: "Real-world LLM usage, tool evaluation, and security considerations", isHighSignal: true },
  { name: "Lilian Weng's Blog", type: "blog", description: "Deep technical explainers on agents, RLHF, diffusion models from an OpenAI researcher", audience: "Researchers and advanced practitioners", frequency: "Monthly", url: "https://lilianweng.github.io", subscriberCount: null, host: "Lilian Weng", bestFor: "Graduate-level depth on core AI concepts — worth reading multiple times", isHighSignal: true },
  { name: "OpenAI Blog", type: "blog", description: "Official blog covering model releases, safety research, and API updates", audience: "Developers and researchers", frequency: "Weekly", url: "https://openai.com/blog", subscriberCount: null, host: null, bestFor: "Official model releases and safety research from the most influential AI lab", isHighSignal: true },
  { name: "Lex Fridman Podcast", type: "podcast", description: "Long-form conversations on AI, science, and philosophy with the world's most influential thinkers", audience: "Broad technical and general audience", frequency: "Weekly", url: "https://lexfridman.com/podcast", subscriberCount: "4.9M YouTube", host: "Lex Fridman", bestFor: "Deep, unhurried conversations with AI's most important figures — Sam Altman, Karpathy, Musk", isHighSignal: true },
  { name: "Dwarkesh Podcast", type: "podcast", description: "Dense, research-backed interviews with frontier AI figures and economists", audience: "Technically sophisticated readers", frequency: "Monthly", url: "https://www.dwarkeshpatel.com", subscriberCount: "300K+", host: "Dwarkesh Patel", bestFor: "The deepest conversations in AI — views that don't appear in press releases", isHighSignal: true },
  { name: "Latent Space Podcast", type: "podcast", description: "Weekly AI engineering show for builders — technical depth on what's being built", audience: "AI engineers and builders", frequency: "Weekly", url: "https://latent.space", subscriberCount: "176K+", host: "swyx & Alessio", bestFor: "What AI engineers are actually building and shipping", isHighSignal: true },
  { name: "Hard Fork", type: "podcast", description: "NYT tech reporters breaking down AI and tech news for a mixed audience", audience: "General tech-savvy audience", frequency: "Weekly", url: "https://www.nytimes.com/column/hard-fork", subscriberCount: null, host: "Kevin Roose & Casey Newton", bestFor: "Accessible AI news context — excellent for non-technical community members", isHighSignal: false },
  { name: "No Priors", type: "podcast", description: "AI investing and company-building conversations with top VCs and lab founders", audience: "Founders and investors", frequency: "Weekly", url: "https://www.nopriorspod.com", subscriberCount: null, host: "Sarah Guo & Elad Gil", bestFor: "AI investing landscape and company-building strategy from top VCs", isHighSignal: false },
  { name: "Matt Wolfe (Future Tools)", type: "youtube", description: "Best general-audience AI news breakdowns and tool reviews. Highly accessible.", audience: "General audience", frequency: "Multiple per week", url: "https://youtube.com/@mreflow", subscriberCount: "810K+", host: "Matt Wolfe", bestFor: "Accessible AI tool reviews and news — best starting point for non-technical followers", isHighSignal: false },
  { name: "Two Minute Papers", type: "youtube", description: "Academic AI research summarized in short, engaging videos", audience: "Research-curious audience", frequency: "Weekly", url: "https://youtube.com/@TwoMinutePapers", subscriberCount: null, host: "Karoly Zsolnai-Fehér", bestFor: "Stay current on AI research papers without reading them yourself", isHighSignal: false },
  { name: "Techmeme", type: "news_site", description: "Real-time tech news aggregator — updated continuously, best tech news hub overall", audience: "All tech professionals", frequency: "Real-time", url: "https://techmeme.com", subscriberCount: null, host: null, bestFor: "Best overall tech news aggregator — everything important surfaces here", isHighSignal: true },
  { name: "VentureBeat AI", type: "news_site", description: "Product launches, funding rounds, and enterprise AI adoption coverage", audience: "Enterprise tech leaders", frequency: "Daily", url: "https://venturebeat.com/ai", subscriberCount: null, host: null, bestFor: "Enterprise AI adoption, product launches, and funding news", isHighSignal: false },
  { name: "One Useful Thing", type: "newsletter", description: "Ethan Mollick's rigorous, experiment-backed essays on how AI is changing knowledge work, education, and creativity. One of the most widely shared AI reads among non-technical professionals.", audience: "Knowledge workers, educators, managers", frequency: "Weekly", url: "https://www.oneusefulthing.org", subscriberCount: "400K+", host: "Ethan Mollick", bestFor: "How AI changes real work — backed by experiments, not hype; essential for anyone applying AI in professional settings", isHighSignal: true },
  { name: "Prompt Capital", type: "newsletter", description: "India-focused AI newsletter decoding global AI trends, policy, and investments — including Budget AI analysis, Google's century bonds, and frontier model developments.", audience: "Indian tech professionals and investors", frequency: "Weekly", url: "https://promptcapital.substack.com", subscriberCount: null, host: "Rohit Singh", bestFor: "India-angle AI coverage — policy, investment, and global AI developments translated for the Indian context", isHighSignal: false },
  { name: "Dario Amodei's Essays", type: "blog", description: "Long-form essays from Anthropic's CEO on the philosophy and future of AI. 'Machines of Loving Grace' and 'The Adolescence of Technology' are essential reads for anyone tracking AGI timelines.", audience: "Researchers, founders, policy thinkers", frequency: "Occasional", url: "https://darioamodei.com", subscriberCount: null, host: "Dario Amodei", bestFor: "The most rigorous long-form thinking on what powerful AI means for humanity — primary source for Anthropic's worldview", isHighSignal: true },
  { name: "The Neuron", type: "newsletter", description: "Witty, Morning Brew-style daily AI newsletter covering industry shifts and major model releases in under five minutes. Sharp, punchy, and highly readable.", audience: "Business professionals and general tech audience", frequency: "Daily", url: "https://www.theneurondaily.com", subscriberCount: "500K+", host: null, bestFor: "Fast, engaging daily AI briefing with personality — best for busy professionals who want signal without the dry technical jargon", isHighSignal: true },
  { name: "AlphaSignal", type: "newsletter", description: "Weekly newsletter using its own AI algorithms to surface the most significant research papers and technical breakthroughs trending in the R&D community.", audience: "AI researchers and advanced practitioners", frequency: "Weekly", url: "https://alphasignal.ai", subscriberCount: "200K+", host: null, bestFor: "AI-curated research discovery — find the papers that matter before they become mainstream, without reading arXiv yourself", isHighSignal: true },
];

const communities = [
  { name: "r/ChatGPT", platform: "reddit", memberCount: "9.9M+", description: "Broad ChatGPT news, prompting tips, and community reactions", url: "https://reddit.com/r/ChatGPT", bestFor: "General ChatGPT news and community prompting tips" },
  { name: "r/OpenAI", platform: "reddit", memberCount: "2.3M+", description: "OpenAI model updates and developer discussions", url: "https://reddit.com/r/OpenAI", bestFor: "OpenAI model updates and API discussions" },
  { name: "r/Artificial", platform: "reddit", memberCount: "1.1M+", description: "General AI news and debates across all labs and research areas", url: "https://reddit.com/r/Artificial", bestFor: "Broad AI news and cross-lab discussions" },
  { name: "r/LocalLLaMA", platform: "reddit", memberCount: "500K+", description: "Open-source and self-hosted LLM community — fine-tuning, quantization, deployment", url: "https://reddit.com/r/LocalLLaMA", bestFor: "Running LLMs locally, open-source models, fine-tuning" },
  { name: "OpenAI Discord", platform: "discord", memberCount: "100K+", description: "Developer discussions, API help, and feature previews", url: "https://discord.gg/openai", bestFor: "Developer API help and early access to OpenAI features" },
  { name: "Hugging Face Discord", platform: "discord", memberCount: "50K+", description: "Open-source ML, NLP, and dataset sharing community", url: "https://discord.gg/huggingface", bestFor: "Open-source model sharing, dataset collaboration, ML research" },
  { name: "Learn AI Together", platform: "discord", memberCount: "30K+", description: "Community-driven learning with weekly reading groups and job postings", url: "https://discord.gg/learnaitogether", bestFor: "Structured AI learning, reading groups, and job hunting" },
  { name: "Latent Space Discord", platform: "discord", memberCount: "20K+", description: "AI engineering community for builders, linked to the Latent Space podcast", url: "https://discord.gg/latentspace", bestFor: "AI engineering discussions for serious builders" },
  { name: "CC For Everyone", platform: "community", memberCount: null, description: "Community dedicated to making Claude Code accessible to all — tutorials, tips, and resources for non-engineers using AI coding tools", url: "https://ccforeveryone.com", bestFor: "Getting started with Claude Code and AI-assisted development as a non-technical user" },
];

export async function seedIfEmpty() {
  const existing = await db.select().from(peopleTable).limit(1);
  if (existing.length > 0) return;

  logger.info("Database is empty — running seed...");

  await db.insert(peopleTable).values(people);
  await db.insert(sourcesTable).values(sources);
  await db.insert(communitiesTable).values(communities);

  logger.info({ people: people.length, sources: sources.length, communities: communities.length }, "Seed complete");
}

export async function updateSeedData() {
  const existingPeople = await db.select({ name: peopleTable.name }).from(peopleTable);
  const existingNames = new Set(existingPeople.map((p) => p.name));
  const newPeople = people.filter((p) => !existingNames.has(p.name));
  if (newPeople.length > 0) {
    await db.insert(peopleTable).values(newPeople);
    logger.info({ count: newPeople.length, names: newPeople.map((p) => p.name) }, "Added new people");
  }

  const existingSources = await db.select({ name: sourcesTable.name }).from(sourcesTable);
  const existingSourceNames = new Set(existingSources.map((s) => s.name));
  const newSources = sources.filter((s) => !existingSourceNames.has(s.name));
  if (newSources.length > 0) {
    await db.insert(sourcesTable).values(newSources);
    logger.info({ count: newSources.length, names: newSources.map((s) => s.name) }, "Added new sources");
  }

  const existingCommunities = await db.select({ name: communitiesTable.name }).from(communitiesTable);
  const existingCommunityNames = new Set(existingCommunities.map((c) => c.name));
  const newCommunities = communities.filter((c) => !existingCommunityNames.has(c.name));
  if (newCommunities.length > 0) {
    await db.insert(communitiesTable).values(newCommunities);
    logger.info({ count: newCommunities.length, names: newCommunities.map((c) => c.name) }, "Added new communities");
  }
}
