import { db } from "@workspace/db";
import { peopleTable, sourcesTable, communitiesTable } from "@workspace/db/schema";
import { eq } from "drizzle-orm";
import { logger } from "./logger";

const people = [
  { name: "Geoffrey Hinton", role: "AI Pioneer, Former VP & Fellow at Google", organization: "University of Toronto", category: "godfathers", bio: "Co-creator of backpropagation and deep neural networks. Shared the 2018 Turing Award. Left Google in 2023 to speak freely about AI risks.", stance: "Existential risk alarm — believes AI poses genuine existential dangers to humanity", twitterHandle: "geoffreyhinton", twitterFollowers: "700K+", primaryPlatform: "X + LinkedIn", bestFor: "Understanding the deep roots of neural networks and the most serious safety concerns from someone who built the foundations", isSpotlight: true },
  { name: "Yann LeCun", role: "Chief AI Scientist at Meta", organization: "Meta / NYU", category: "godfathers", bio: "Creator of convolutional neural networks (CNNs), the backbone of all computer vision. Turing Award winner 2018. Highly active and combative debater on X.", stance: "Contrarian — argues current LLMs are fundamentally limited and not on the path to AGI", twitterHandle: "ylecun", twitterFollowers: "972K", primaryPlatform: "X", bestFor: "Alternative view on LLM limitations; deep expertise in vision and architecture design", isSpotlight: false },
  { name: "Yoshua Bengio", role: "Scientific Director at MILA", organization: "MILA / Université de Montréal", category: "godfathers", bio: "Solved the vanishing gradient problem. Founded MILA, the world's top AI research institute. Writes long-form safety essays on LinkedIn.", stance: "Safety-focused, measured, and deeply concerned about misaligned AI", twitterHandle: "yoshuabengio", twitterFollowers: "200K+", primaryPlatform: "LinkedIn", bestFor: "Deep, nuanced perspective on AI safety from one of the field's most credible voices", isSpotlight: false },
  { name: "Fei-Fei Li", role: "Co-Director, Stanford HAI", organization: "Stanford University", category: "godfathers", bio: "Created ImageNet — the dataset that triggered the deep learning explosion. Runs Stanford's Human-Centered AI Institute.", stance: "Human-centered AI; champions diversity, inclusion, and responsible deployment", twitterHandle: "drfeifei", twitterFollowers: "350K+", primaryPlatform: "X + LinkedIn", bestFor: "Human-centered AI perspective; responsible deployment of powerful systems", isSpotlight: false },
  { name: "Andrew Ng", role: "Founder, DeepLearning.AI & AI Fund", organization: "DeepLearning.AI", category: "godfathers", bio: "Co-founded Google Brain and Coursera. Built Baidu's AI division. Writes The Batch newsletter weekly. Best bridge between research and practice.", stance: "Optimistic pragmatist — focuses on AI democratization and practical deployment", twitterHandle: "AndrewYNg", twitterFollowers: "800K+", primaryPlatform: "X + LinkedIn", bestFor: "Bridging AI research and real-world application; weekly signal in The Batch", isSpotlight: false },
  { name: "Sam Altman", role: "CEO, OpenAI", organization: "OpenAI", category: "lab_ceos", bio: "#1 on AI Magazine's Top 100 AI Leaders 2026. Led GPT-4, GPT-5 launches and $40B funding round at $300B valuation.", stance: "Cautiously optimistic — advocates for responsible development while racing toward AGI", twitterHandle: "sama", twitterFollowers: "3M+", primaryPlatform: "X", bestFor: "First-hand view of OpenAI's direction; candid takes on frontier AI development", isSpotlight: false },
  { name: "Dario Amodei", role: "CEO, Anthropic", organization: "Anthropic", category: "lab_ceos", bio: "Safety-first alternative to OpenAI. Raised $27.3B. Thoughtful long-form blogger. Shapes Claude's Constitutional AI direction.", stance: "Safety-first — methodical, research-driven, deeply concerned about alignment", twitterHandle: "darioamodei", twitterFollowers: "200K+", primaryPlatform: "Blog + X", bestFor: "Safety-focused perspective on frontier AI; understanding how Anthropic thinks about alignment", isSpotlight: false },
  { name: "Demis Hassabis", role: "CEO, Google DeepMind", organization: "Google DeepMind", category: "lab_ceos", bio: "2024 Nobel Prize in Chemistry for AlphaFold. Knighted in 2024. Leads 6,000-person team toward AGI. Co-founded DeepMind in 2010.", stance: "Scientific optimism — believes AGI is achievable and will be profoundly beneficial", twitterHandle: "demishassabis", twitterFollowers: "500K+", primaryPlatform: "X", bestFor: "Scientific AI research perspective; DeepMind's moonshot approach to AGI", isSpotlight: false },
  { name: "Ilya Sutskever", role: "CEO, Safe Superintelligence", organization: "Safe Superintelligence (SSI)", category: "lab_ceos", bio: "Co-created AlexNet, co-founded OpenAI. Left to build SSI — focused purely on safe superintelligence without commercial pressure.", stance: "Safety absolutist — left OpenAI specifically to focus on superintelligence safety without distraction", twitterHandle: "ilyasut", twitterFollowers: "400K+", primaryPlatform: "X", bestFor: "Understanding the most safety-focused frontier lab; what safety-first AGI development looks like", isSpotlight: false },
  { name: "Jensen Huang", role: "CEO, NVIDIA", organization: "NVIDIA", category: "hardware", bio: "#2 on AI Magazine Top 100. Without NVIDIA's GPUs the current AI wave doesn't exist. His keynotes are industry state-of-the-union addresses.", stance: "Bullish on AI's transformative power; believes we are at an inflection point in computing history", twitterHandle: "nvidia", twitterFollowers: "10M+ (NVIDIA)", primaryPlatform: "LinkedIn + Keynotes", bestFor: "Hardware supply chain; understanding what compute constraints mean for AI development pace", isSpotlight: false },
  { name: "Lisa Su", role: "CEO, AMD", organization: "AMD", category: "hardware", bio: "#10 on AI Magazine Top 100. Main challenger to NVIDIA's AI chip dominance. Leading AMD's aggressive push into AI accelerators.", stance: "Competitive optimist — AMD can challenge NVIDIA's dominance in AI compute", twitterHandle: "lisasu", twitterFollowers: "100K+", primaryPlatform: "LinkedIn", bestFor: "Alternative to NVIDIA compute narrative; GPU market dynamics and AI chip competition", isSpotlight: false },
  { name: "Andrej Karpathy", role: "Founder, Eureka Labs", organization: "Eureka Labs", category: "builders", bio: "Coined 'vibe coding.' Ex-Tesla AI Director, ex-OpenAI. 1.3M followers on X. Produces the most trusted deep technical LLM explainers.", stance: "Enthusiastically optimistic — sees AI tools as fundamentally changing how software is built", twitterHandle: "karpathy", twitterFollowers: "1.3M", primaryPlatform: "X + YouTube", bestFor: "Deep technical LLM understanding; best bridge between research and engineering practice", isSpotlight: false },
  { name: "Simon Willison", role: "Creator of Datasette; Co-creator of Django", organization: "Independent", category: "builders", bio: "Writes simonwillison.net daily — 575+ posts tagged 'llm'. The most consistent practical LLM usage tracker on the internet.", stance: "Pragmatic explorer — focused on what actually works today, including security considerations", twitterHandle: "simonw", twitterFollowers: "200K+", primaryPlatform: "Blog", bestFor: "Daily practical LLM usage, tool-building, prompt injection risks — the 'what works today' source", isSpotlight: false },
  { name: "swyx (Shawn Wang)", role: "Co-host, Latent Space Podcast", organization: "Latent Space", category: "builders", bio: "Coined 'AI Engineer.' Latent Space is the #1 podcast for AI engineers with 176K+ subscribers. Deeply embedded in the AI engineering community.", stance: "Builder-first — focused on what practitioners need to build and ship AI products", twitterHandle: "swyx", twitterFollowers: "250K+", primaryPlatform: "X + Substack + Podcast", bestFor: "AI engineering culture and practice; what builders are actually shipping", isSpotlight: false },
  { name: "Gary Marcus", role: "Cognitive Scientist & AI Critic", organization: "NYU (Emeritus)", category: "builders", bio: "The most credible AI skeptic. Regularly challenges AI hype with rigorous arguments. Essential counterbalance in any balanced feed.", stance: "Critical realist — believes current AI systems are fundamentally brittle and AGI claims are premature", twitterHandle: "GaryMarcus", twitterFollowers: "197K", primaryPlatform: "X + Substack", bestFor: "Credible counterpoint to AI hype; understanding real limitations of current systems", isSpotlight: false },
  { name: "Lilian Weng", role: "Safety Researcher, OpenAI", organization: "OpenAI", category: "builders", bio: "Maintains one of the most respected technical AI blogs. Deep explainers on agents, RLHF, diffusion models. Monthly but extremely high depth.", stance: "Research-first — rigorous empirical approach to understanding AI systems", twitterHandle: "lilianweng", twitterFollowers: "150K+", primaryPlatform: "Blog", bestFor: "Deep technical explainers on agents, RLHF, prompting — graduate-level depth made accessible", isSpotlight: false },
  { name: "Dwarkesh Patel", role: "Podcaster", organization: "Dwarkesh Podcast", category: "builders", bio: "Called 'Silicon Valley's favourite podcaster' by The Economist. Dense, research-backed interviews with the most important AI figures.", stance: "Curious empiricist — uses dense research to draw out views that don't appear in press releases", twitterHandle: "dwarkesh_sp", twitterFollowers: "200K+", primaryPlatform: "Podcast + Substack", bestFor: "The deepest conversations in AI — Karpathy, Sutskever, Zuckerberg like you've never heard them", isSpotlight: false },
  { name: "Nate Liason", role: "Author & Vibe Coding Educator", organization: "Independent", category: "vibe_coders", bio: "75.8K followers on X. Teaches vibe coding workflows to non-technical builders. Focuses on practical no-code-adjacent AI building.", stance: null, twitterHandle: "nateliason", twitterFollowers: "75.8K", primaryPlatform: "X + Newsletter", bestFor: "Practical vibe coding workflows for non-technical builders", isSpotlight: false },
  { name: "Peter Steinberger", role: "Developer & Vibe Coder", organization: "Independent", category: "vibe_coders", bio: "41.4K followers on X. Bridges between vibe coding and serious agentic engineering. Shows what professionals can build with AI assistance.", stance: null, twitterHandle: "steipete", twitterFollowers: "41.4K", primaryPlatform: "X", bestFor: "Professional-grade vibe coding; what serious engineers can ship with AI tools", isSpotlight: false },
  { name: "Matt Palmer", role: "Vibe Coding Lead at Replit", organization: "Replit", category: "vibe_coders", bio: "28.2K followers on X. Works on vibe coding product at Replit — inside view on the tools powering the movement.", stance: null, twitterHandle: "mattppal", twitterFollowers: "28.2K", primaryPlatform: "X", bestFor: "Inside view on vibe coding tooling; what Replit is building for AI-assisted development", isSpotlight: false },
  { name: "Aravind Srinivas", role: "CEO, Perplexity AI", organization: "Perplexity AI", category: "lab_ceos", bio: "Built Perplexity into a search-disrupting AI company valued at $14B. Former researcher at OpenAI and Google DeepMind. Launched Perplexity Computer as a safer alternative to AI computer-use tools.", stance: "Pragmatic optimist — believes AI can fundamentally reimagine how we access and synthesize information", twitterHandle: "AravSrinivas", twitterFollowers: "300K+", primaryPlatform: "X + LinkedIn", bestFor: "AI search, information retrieval, and the future of how we access knowledge", isSpotlight: false },
  { name: "Guillermo Rauch", role: "CEO, Vercel", organization: "Vercel", category: "builders", bio: "Creator of Next.js — the framework powering a huge share of the AI-era web. Forbes profile March 2026. Building the infrastructure layer for AI-generated frontends.", stance: "Infrastructure optimist — AI dramatically lowers the floor for web creation", twitterHandle: "rauchg", twitterFollowers: "500K+", primaryPlatform: "X", bestFor: "AI-era web development and frontend infrastructure; where web tooling is heading next", isSpotlight: false },
  { name: "Ethan Mollick", role: "Professor, Wharton; Author of Co-Intelligence", organization: "Wharton School, UPenn", category: "builders", bio: "Writes One Useful Thing — the most practical AI learning resource for knowledge workers. Author of Co-Intelligence. Runs real experiments on how AI changes work, education, and creativity.", stance: "Evidence-based optimist — rigorously tests what AI can and cannot do rather than speculating", twitterHandle: "emollick", twitterFollowers: "600K+", primaryPlatform: "Substack + X", bestFor: "How AI changes knowledge work and education — backed by real experiments, not hype", isSpotlight: false },
  { name: "Sigrid Jin", role: "Developer & World's Most Active Claude Code User", organization: "Independent", category: "vibe_coders", bio: "Reported by WSJ to have personally used 25 billion Claude tokens in a year. When Anthropic accidentally leaked their source code via npm, he rewrote the entire thing in Python from scratch before sunrise — the resulting 'claw-code' repo hit 30,000 GitHub stars faster than any repo in history.", stance: null, twitterHandle: "sigridjin", twitterFollowers: "50K+", primaryPlatform: "GitHub + X", bestFor: "What's possible at the absolute frontier of AI-assisted engineering; living proof of AI's productivity multiplier", isSpotlight: false },
  { name: "Rowan Cheung", role: "Founder, The Rundown AI", organization: "The Rundown AI", category: "builders", bio: "Built The Rundown AI into one of the world's largest AI newsletters with 1.75M+ subscribers. One of the most-followed AI curators on X. Daily signal on what matters most in AI — tools, models, and industry moves.", stance: "Pragmatic builder — focused on surfacing what's actionable for busy professionals and founders", twitterHandle: "rowancheung", twitterFollowers: "500K+", primaryPlatform: "X + Newsletter", bestFor: "Daily curated AI signal for founders and non-technical professionals — the fastest way to stay current without deep technical knowledge", isSpotlight: false, imageUrl: "https://unavatar.io/x/rowancheung" },

  // --- Expanded roster ---
  { name: "Elon Musk", role: "CEO, xAI; Owner, X Corp", organization: "xAI / X", category: "lab_ceos", bio: "Founded xAI and launched Grok, a direct OpenAI competitor. Owner of X (Twitter), which gives him unparalleled reach to shape AI narratives. Most followed tech figure on X with 200M+ followers. His Starlink and Tesla AI divisions make him a hardware-to-model vertical stack unlike anyone else.", stance: "Accelerationist with safety caveats — sued OpenAI over mission drift, wants open-source AGI but races toward it simultaneously", twitterHandle: "elonmusk", twitterFollowers: "200M+", primaryPlatform: "X", bestFor: "Understanding the xAI / Grok trajectory and the political economy of AI ownership", isSpotlight: false, imageUrl: "https://unavatar.io/x/elonmusk" },
  { name: "Mustafa Suleyman", role: "CEO, Microsoft AI", organization: "Microsoft", category: "lab_ceos", bio: "Co-founded Google DeepMind, then built Inflection AI (Pi). Hired by Microsoft in 2024 to run all consumer AI. Author of 'The Coming Wave' — one of the most-read AI policy books of the decade. Shapes Copilot, Bing AI, and Microsoft's consumer AI direction.", stance: "Cautious co-evolutionist — argues AI development must be paired with containment frameworks; coined 'the coming wave'", twitterHandle: "mustafasuleyman", twitterFollowers: "200K+", primaryPlatform: "X + LinkedIn", bestFor: "Microsoft's AI strategy; the policy and governance angle from someone who has built and shipped frontier models", isSpotlight: false, imageUrl: "https://unavatar.io/x/mustafasuleyman" },
  { name: "Clément Delangue", role: "CEO, Hugging Face", organization: "Hugging Face", category: "lab_ceos", bio: "Built Hugging Face into the GitHub of AI — 500K+ models, 150K+ datasets hosted. Valued at $4.5B. The platform that democratized access to every major open-source model from LLaMA to Stable Diffusion.", stance: "Open-source maximalist — believes open models are essential to prevent AI power concentration", twitterHandle: "ClementDelangue", twitterFollowers: "100K+", primaryPlatform: "X + LinkedIn", bestFor: "Open-source AI ecosystem; where models, datasets, and spaces live before going mainstream", isSpotlight: false, imageUrl: "https://unavatar.io/x/ClementDelangue" },
  { name: "Arthur Mensch", role: "CEO, Mistral AI", organization: "Mistral AI", category: "lab_ceos", bio: "Co-founded Mistral AI in 2023 — raised €1B+ and built Europe's leading frontier lab. Mistral 7B proved small open models could rival GPT-3.5. Key figure in European AI sovereignty debates.", stance: "Open, efficient, sovereign — European model that competes with US labs on quality without sacrificing openness", twitterHandle: "arthurmensch", twitterFollowers: "50K+", primaryPlatform: "X", bestFor: "European AI perspective; open-weight frontier models; the alternative to US-only AI infrastructure", isSpotlight: false, imageUrl: "https://unavatar.io/x/arthurmensch" },
  { name: "Greg Brockman", role: "Co-Founder, OpenAI", organization: "OpenAI", category: "lab_ceos", bio: "President and co-founder of OpenAI. Built the technical and organizational infrastructure that produced GPT-4 and beyond. Took a sabbatical in 2024, returned in 2025. One of the most important builders in the history of AI.", stance: "Mission-driven builder — believes in OpenAI's original mission of safe, beneficial AGI for humanity", twitterHandle: "gdb", twitterFollowers: "250K+", primaryPlatform: "X", bestFor: "OpenAI's foundational thinking; how the world's most impactful AI lab was actually built", isSpotlight: false, imageUrl: "https://unavatar.io/x/gdb" },
  { name: "Mira Murati", role: "Founder, Thinking Machines Lab", organization: "Thinking Machines Lab", category: "lab_ceos", bio: "Former CTO of OpenAI — oversaw GPT-4, DALL-E, Sora, and ChatGPT launches. Left in late 2024 to found Thinking Machines Lab. One of the most credentialed AI executives ever to launch an independent lab.", stance: "Thoughtful pragmatist — focused on making AI systems that are genuinely useful and safe in practice", twitterHandle: "miramurati", twitterFollowers: "200K+", primaryPlatform: "X + LinkedIn", bestFor: "What GPT-4 and Sora looked like from the inside; what the next wave of AI products will require", isSpotlight: false, imageUrl: "https://unavatar.io/x/miramurati" },
  { name: "Lex Fridman", role: "AI Researcher & Podcaster", organization: "MIT / Independent", category: "builders", bio: "MIT researcher turned podcast host with 4.9M YouTube subscribers. Conducts the longest, most in-depth AI conversations on the internet — with Musk, Altman, Karpathy, Hinton, and more. His interviews often contain the most unguarded views from AI's key figures.", stance: "Curious optimist — explores AI's philosophical, technical, and existential dimensions with equal rigor", twitterHandle: "lexfridman", twitterFollowers: "3M+", primaryPlatform: "YouTube + Podcast + X", bestFor: "The deepest unguarded conversations with AI's most important figures — often reveals views not seen in press releases", isSpotlight: false, imageUrl: "https://unavatar.io/x/lexfridman" },
  { name: "Jack Clark", role: "Co-Founder, Anthropic; Author, Import AI", organization: "Anthropic", category: "builders", bio: "Co-founded Anthropic with Dario Amodei. Writes Import AI — the most respected weekly AI policy and research newsletter, running since 2016. Former OpenAI Policy Director. Shapes how governments think about AI risk.", stance: "Safety-conscious realist — tracks AI capability growth carefully and advocates for serious policy responses", twitterHandle: "jackclarkSF", twitterFollowers: "60K+", primaryPlatform: "Newsletter + X", bestFor: "AI policy and frontier research tracking — Import AI is essential reading for anyone who wants to understand where AI governance is heading", isSpotlight: false, imageUrl: "https://unavatar.io/x/jackclarkSF" },
  { name: "François Chollet", role: "AI Researcher; Creator of Keras", organization: "Independent (ex-Google)", category: "builders", bio: "Created Keras, used by millions of ML practitioners. Runs the ARC Prize — a benchmark for measuring general intelligence that LLMs still largely fail. Writes rigorous critiques of AI hype grounded in decades of research.", stance: "Measured skeptic — argues LLMs are not on the path to general intelligence; ARC Prize quantifies the gap", twitterHandle: "fchollet", twitterFollowers: "600K+", primaryPlatform: "X", bestFor: "Technical grounding on what AI can and cannot do; the ARC benchmark as a reality check on AGI claims", isSpotlight: false, imageUrl: "https://unavatar.io/x/fchollet" },
  { name: "Kara Swisher", role: "Tech Journalist & Podcaster", organization: "Independent", category: "builders", bio: "The most fearless AI interviewer in journalism. Hosts On with Kara Swisher and co-hosts Pivot. Has held every major AI CEO accountable in ways no one else has. Her interviews with Altman, Musk, and Zuckerberg are must-listens.", stance: "Skeptical watchdog — believes AI companies must be held accountable for societal impact; deeply critical of unchecked power", twitterHandle: "karaswisher", twitterFollowers: "1.8M+", primaryPlatform: "Podcast + X", bestFor: "Hard questions no one else asks — accountability journalism in an era of AI hype", isSpotlight: false, imageUrl: "https://unavatar.io/x/karaswisher" },
  { name: "Ben Thompson", role: "Founder, Stratechery", organization: "Stratechery", category: "builders", bio: "Writes Stratechery — the most influential tech strategy newsletter, read by every major VC and CEO. Has developed the clearest analytical framework for how AI restructures industries. His 'AI and the Big Five' and 'Aggregation Theory' essays are required reading.", stance: "Strategic analyst — views AI through the lens of business model disruption, market power, and platform theory", twitterHandle: "benthompson", twitterFollowers: "300K+", primaryPlatform: "Newsletter + Podcast", bestFor: "The best strategic analysis of how AI reshapes business models, markets, and competitive dynamics", isSpotlight: false, imageUrl: "https://unavatar.io/x/benthompson" },
  { name: "Sebastian Raschka", role: "ML Researcher & Educator", organization: "Lightning AI", category: "builders", bio: "Author of 'Machine Learning with PyTorch and Scikit-Learn.' Writes Ahead of AI — the most hands-on LLM tutorial newsletter. Researcher at Lightning AI. Makes cutting-edge ML accessible with real code and intuition.", stance: "Practitioner-first — focuses on what actually works, with working code not just theory", twitterHandle: "rasbt", twitterFollowers: "100K+", primaryPlatform: "Newsletter + X", bestFor: "Hands-on LLM implementation with real code — the best newsletter for engineers who want to understand the mechanics", isSpotlight: false, imageUrl: "https://unavatar.io/x/rasbt" },
  { name: "Nathan Lambert", role: "RLHF Researcher", organization: "Allen Institute for AI (AI2)", category: "builders", bio: "Leads RLHF and post-training research at AI2. Writes Interconnects — the clearest newsletter explaining how models are trained after pretraining. Was at HuggingFace before AI2. Co-author of key RLHF papers.", stance: "Open research advocate — believes the post-training process should be understood publicly, not locked in labs", twitterHandle: "natolambert", twitterFollowers: "60K+", primaryPlatform: "Newsletter + X", bestFor: "The clearest explanations of RLHF, post-training, and how model behavior is shaped — essential for understanding alignment in practice", isSpotlight: false, imageUrl: "https://unavatar.io/x/natolambert" },
  { name: "Harrison Chase", role: "CEO, LangChain", organization: "LangChain", category: "builders", bio: "Created LangChain — the most-used AI application framework in the world with 90K+ GitHub stars. Building LangSmith for production AI observability. His work defines how engineers orchestrate LLM applications.", stance: "Pragmatic builder — focused on making LLM applications reliable, observable, and production-ready", twitterHandle: "hwchase17", twitterFollowers: "40K+", primaryPlatform: "X + GitHub", bestFor: "LLM application architecture, agent orchestration, and production AI engineering", isSpotlight: false, imageUrl: "https://unavatar.io/x/hwchase17" },
  { name: "Nat Friedman", role: "Co-Founder, AI Grant; Former CEO, GitHub", organization: "AI Grant", category: "builders", bio: "Former CEO of GitHub (acquired by Microsoft). Co-runs AI Grant with Daniel Gross — one of the most active early-stage AI investment funds. Funded and mentored dozens of AI startups. Legendary AI optimist and hacker.", stance: "Aggressive optimist — believes AI will accelerate science and human capability faster than almost anyone predicts", twitterHandle: "natfriedman", twitterFollowers: "300K+", primaryPlatform: "X", bestFor: "Early-stage AI startup landscape; what the smartest AI investors are betting on next", isSpotlight: false, imageUrl: "https://unavatar.io/x/natfriedman" },
  { name: "Emad Mostaque", role: "Founder, Stability AI", organization: "Stability AI", category: "lab_ceos", bio: "Founded Stability AI and launched Stable Diffusion — the open-source image generation model that democratized generative AI. Left Stability AI in 2024. Outspoken advocate for open-source AI and decentralized compute.", stance: "Open-source maximalist — believes AI should be owned by no one and available to everyone", twitterHandle: "EMostaque", twitterFollowers: "250K+", primaryPlatform: "X", bestFor: "Open-source generative AI history; the case for decentralized AI development", isSpotlight: false, imageUrl: "https://unavatar.io/x/EMostaque" },
  { name: "Jürgen Schmidhuber", role: "AI Researcher; Director, KAUST AI Initiative", organization: "KAUST", category: "godfathers", bio: "Invented LSTM (Long Short-Term Memory) — the architecture that powered speech recognition, translation, and the first wave of practical deep learning. Has been doing AI research since 1987. Runs the KAUST AI center and is famously outspoken about credit attribution in AI history.", stance: "Historical corrector — insists foundational AI credit is systematically misattributed; believes recursive self-improvement leads to superintelligence", twitterHandle: "SchmidhuberAI", twitterFollowers: "30K+", primaryPlatform: "X + Blog", bestFor: "Understanding where deep learning really came from; LSTM and the foundations of modern sequence models", isSpotlight: false, imageUrl: "https://unavatar.io/x/SchmidhuberAI" },
  { name: "Reid Hoffman", role: "Co-Founder, LinkedIn; Partner, Greylock", organization: "Greylock Partners", category: "builders", bio: "Co-founded LinkedIn (sold to Microsoft for $26B). Partner at Greylock, early investor in OpenAI, Inflection AI, and dozens of AI startups. Author of 'Impromptu' written with GPT-4. One of Silicon Valley's most connected AI thinkers.", stance: "Collaborative optimist — believes AI amplifies human capability and the key challenge is ensuring benefits are widely shared", twitterHandle: "reidhoffman", twitterFollowers: "800K+", primaryPlatform: "X + LinkedIn + Podcast", bestFor: "AI investment landscape; how AI changes business networks and human collaboration", isSpotlight: false, imageUrl: "https://unavatar.io/x/reidhoffman" },
  { name: "Paul Graham", role: "Co-Founder, Y Combinator", organization: "Y Combinator", category: "builders", bio: "Funded Airbnb, Stripe, Dropbox, Reddit, OpenAI. Writes the most-shared essays in startup culture — 'Do Things That Don't Scale,' 'Keep Your Identity Small.' His takes on AI's impact on programming and startups carry outsized influence.", stance: "Pragmatic futurist — writes about how AI changes what it means to be a programmer and a founder", twitterHandle: "paulg", twitterFollowers: "1.7M+", primaryPlatform: "X + Essays", bestFor: "How AI changes software development, startups, and what skills remain valuable in an automated world", isSpotlight: false, imageUrl: "https://unavatar.io/x/paulg" },
  { name: "Allie K. Miller", role: "AI Advisor & Investor", organization: "Independent", category: "builders", bio: "Former Amazon AI leader. One of LinkedIn's top AI voices with 1M+ followers. Translates complex AI developments into business strategy. Advises Fortune 500 companies on AI adoption and investment.", stance: "Practical optimist — focused on enterprise AI adoption, workforce transformation, and making AI work in real organizations", twitterHandle: "alliekmiller", twitterFollowers: "400K+", primaryPlatform: "LinkedIn + X", bestFor: "Enterprise AI adoption strategy; how large organizations actually deploy and benefit from AI tools", isSpotlight: false, imageUrl: "https://unavatar.io/x/alliekmiller" },
  { name: "Jim Keller", role: "CEO, Tenstorrent", organization: "Tenstorrent", category: "hardware", bio: "The chip designer's chip designer. Architected AMD Zen, Apple A4/A5, and Tesla's Autopilot chip. Now leading Tenstorrent building next-gen AI accelerators. Widely regarded as the most gifted CPU/chip architect alive.", stance: "Hardware maximalist — believes chip architecture innovation is the primary lever for the next decade of AI", twitterHandle: "jimkxa", twitterFollowers: "100K+", primaryPlatform: "X + Interviews", bestFor: "Hardware architecture and the chip-level constraints on AI progress — insights no software person can replicate", isSpotlight: false, imageUrl: "https://unavatar.io/x/jimkxa" },
  { name: "Chris Olah", role: "AI Safety Researcher", organization: "Anthropic", category: "builders", bio: "Pioneer of mechanistic interpretability — the science of understanding what is actually happening inside neural networks. Co-founded Distill (the best ML publication ever). His circuits research at Anthropic is defining the field of AI interpretability.", stance: "Safety through understanding — believes we must deeply understand AI systems before we can trust them", twitterHandle: "ch402", twitterFollowers: "80K+", primaryPlatform: "Blog", bestFor: "Mechanistic interpretability — the frontier of understanding what neural networks actually compute inside", isSpotlight: false, imageUrl: "https://unavatar.io/x/ch402" },
  { name: "George Hotz", role: "Founder, comma.ai", organization: "comma.ai / tinygrad", category: "vibe_coders", bio: "First person to jailbreak the iPhone and hack the PS3. Founded comma.ai — open-source autonomous driving for consumer cars. Built tinygrad, a minimal deep learning framework. Streams coding on Twitch. The original hacker turned AI builder.", stance: "Hacker pragmatist — ships fast, questions everything, and believes open-source beats closed labs", twitterHandle: "realGeorgeHotz", twitterFollowers: "400K+", primaryPlatform: "X + Twitch", bestFor: "Hacker culture meets AI; open-source autonomy and the minimalist approach to deep learning", isSpotlight: false, imageUrl: "https://unavatar.io/x/realGeorgeHotz" },
  { name: "Stuart Russell", role: "Professor & Director, CHAI", organization: "UC Berkeley", category: "godfathers", bio: "Co-author of 'Artificial Intelligence: A Modern Approach' — the AI textbook used in 1,500+ universities. Directs the Center for Human-Compatible AI (CHAI). Author of 'Human Compatible,' the most rigorous book on the alignment problem.", stance: "Alignment realist — the central problem of AI is ensuring machines pursue what humans actually want", twitterHandle: "stuartrussell42", twitterFollowers: "30K+", primaryPlatform: "Books + Talks", bestFor: "Foundational AI theory and the alignment problem explained rigorously — essential background for understanding AI safety debates", isSpotlight: false, imageUrl: "https://unavatar.io/x/stuartrussell42" },
  { name: "Joy Buolamwini", role: "Founder, Algorithmic Justice League", organization: "Algorithmic Justice League", category: "builders", bio: "MIT Media Lab researcher who exposed massive racial and gender bias in facial recognition systems used by Microsoft, IBM, and Amazon. Founded the Algorithmic Justice League. Author of 'Unmasking AI.' Her research forced major tech companies to pause their facial recognition programs.", stance: "Equity advocate — AI must be audited, inclusive, and accountable to those it harms most", twitterHandle: "jovialjoy", twitterFollowers: "100K+", primaryPlatform: "X + Talks", bestFor: "AI bias, fairness, and accountability — the essential voice on whose face AI sees and whose it doesn't", isSpotlight: false, imageUrl: "https://unavatar.io/x/jovialjoy" },
  { name: "Timnit Gebru", role: "Founder & Executive Director, DAIR Institute", organization: "DAIR Institute", category: "builders", bio: "Co-led Google Brain's Ethical AI team before being controversially fired in 2020 over a paper on large language model risks. Founded DAIR (Distributed AI Research) to ensure AI research is done with accountability to affected communities. Co-authored the influential 'Stochastic Parrots' paper.", stance: "Community-centered critic — AI development must center those most harmed by its deployment", twitterHandle: "timnitGebru", twitterFollowers: "200K+", primaryPlatform: "X", bestFor: "AI ethics from an accountability-first lens; why power asymmetries in AI research matter enormously", isSpotlight: false, imageUrl: "https://unavatar.io/x/timnitGebru" },
  { name: "Leopold Aschenbrenner", role: "Author, Situational Awareness", organization: "Independent (ex-OpenAI)", category: "builders", bio: "Former OpenAI safety team member who published 'Situational Awareness' — a 160-page essay arguing AGI is coming by 2027 and we are dangerously unprepared. One of the most widely circulated AI risk documents in the field. Now advising AI safety organizations.", stance: "Urgent alarmist — believes the transition to AGI will happen faster than almost anyone realizes and national security must mobilize now", twitterHandle: "leopoldasch", twitterFollowers: "100K+", primaryPlatform: "Essay + X", bestFor: "The most detailed public case for AGI by 2027 and what geopolitical consequences follow — essential reading on AI timelines", isSpotlight: false, imageUrl: "https://unavatar.io/x/leopoldasch" },
  { name: "Pieter Abbeel", role: "Professor & Co-Founder, Covariant", organization: "UC Berkeley / Covariant", category: "builders", bio: "Professor at UC Berkeley, pioneer in robot learning and deep reinforcement learning. Co-founded Covariant — using AI to make robots that can work in any warehouse. Teaching Award winner. Makes reinforcement learning accessible through online courses.", stance: "Applied optimist — believes robot intelligence will transform physical work as much as LLMs transform knowledge work", twitterHandle: "pabbeel", twitterFollowers: "80K+", primaryPlatform: "X + Courses", bestFor: "Robotics and reinforcement learning — the frontier where AI meets the physical world", isSpotlight: false, imageUrl: "https://unavatar.io/x/pabbeel" },
  { name: "Aidan Gomez", role: "CEO, Cohere", organization: "Cohere", category: "lab_ceos", bio: "Co-author of the original 'Attention Is All You Need' paper — the transformer paper that triggered the current AI revolution. Founded Cohere to bring enterprise LLMs to production at scale. One of the youngest founders with more impact per paper than almost anyone alive.", stance: "Enterprise pragmatist — LLMs must be reliable, private, and deployable in real organizations, not just impressive demos", twitterHandle: "aidangomez", twitterFollowers: "40K+", primaryPlatform: "X + LinkedIn", bestFor: "Enterprise AI deployment and the original transformer architecture — context from one of its inventors", isSpotlight: false, imageUrl: "https://unavatar.io/x/aidangomez" },
  { name: "Kate Crawford", role: "Senior Principal Researcher, Microsoft Research", organization: "Microsoft Research / AI Now Institute", category: "builders", bio: "Author of 'Atlas of AI' — the most rigorous investigation into the material, political, and environmental costs of AI. Co-founded the AI Now Institute. Her research exposes how AI systems encode power, labor exploitation, and extraction.", stance: "Critical theorist — AI reflects and amplifies existing power structures; the infrastructure has enormous hidden costs", twitterHandle: "katecrawford", twitterFollowers: "150K+", primaryPlatform: "X + Books", bestFor: "The political economy of AI — who profits, who is harmed, and what the environmental and labor costs really are", isSpotlight: false, imageUrl: "https://unavatar.io/x/katecrawford" },
  { name: "Marietje Schaake", role: "International Policy Director, Stanford HAI", organization: "Stanford HAI / Tech Policy Press", category: "builders", bio: "Former Member of European Parliament, the most influential digital rights legislator of her era. Now at Stanford HAI shaping global AI governance. Advises the UN, EU, and G7 on AI regulation. Author of 'The Tech Coup.'", stance: "Regulatory realist — AI must be governed like other powerful technologies; self-regulation by companies has failed", twitterHandle: "MarietjeSchaake", twitterFollowers: "100K+", primaryPlatform: "X + LinkedIn", bestFor: "AI policy and regulation — the most credible bridge between European governance, Stanford research, and global AI diplomacy", isSpotlight: false, imageUrl: "https://unavatar.io/x/MarietjeSchaake" },
];

const sources = [
  { name: "The Rundown AI", type: "newsletter", description: "Daily AI news digest covering model releases, research breakthroughs, and industry moves", audience: "Founders, C-suite executives", frequency: "Daily", url: "https://therundown.ai", subscriberCount: "1.75M+", host: null, bestFor: "Executive-level daily AI briefing", isHighSignal: true },
  { name: "TLDR AI", type: "newsletter", description: "Curated daily AI newsletter for technical readers", audience: "Engineers, data scientists", frequency: "Daily", url: "https://tldr.tech/ai", subscriberCount: "1.25M+", host: null, bestFor: "Technical daily digest — fast to read, high signal", isHighSignal: true },
  { name: "The Batch", type: "newsletter", description: "Andrew Ng's weekly newsletter bridging AI research and business application", audience: "Mixed technical and business", frequency: "Weekly", url: "https://deeplearning.ai/the-batch", subscriberCount: "500K+", host: "Andrew Ng", bestFor: "Research-to-practice bridge; best weekly for understanding what research means for builders", isHighSignal: true },
  { name: "Ben's Bites", type: "newsletter", description: "Daily curation of AI tools, products, and news for builders", audience: "Builders, product people", frequency: "Daily", url: "https://bensbites.co", subscriberCount: "100K+", host: "Ben Tossell", bestFor: "New AI tools and product launches — essential for staying on top of the tooling landscape", isHighSignal: true },
  { name: "Latent Space", type: "newsletter", description: "Newsletter and podcast for AI engineers — technical depth on what's being built", audience: "AI engineers", frequency: "Weekly", url: "https://latent.space", subscriberCount: "176K+", host: "swyx & Alessio", bestFor: "AI engineering depth — what practitioners are actually building", isHighSignal: true },
  { name: "Import AI", type: "newsletter", description: "Jack Clark's weekly deep-dive on frontier research, AI risks, and global policy", audience: "Technical leaders and researchers", frequency: "Weekly", url: "https://jack-clark.net", subscriberCount: "50K+", host: "Jack Clark", bestFor: "Frontier research and AI policy — what's happening in the labs and governments", isHighSignal: true },
  { name: "Ahead of AI", type: "newsletter", description: "Sebastian Raschka's hands-on LLM tutorials with real code", audience: "ML practitioners", frequency: "Weekly", url: "https://magazine.sebastianraschka.com", subscriberCount: "50K+", host: "Sebastian Raschka", bestFor: "Hands-on LLM implementation — readable code, not just theory", isHighSignal: false },
  { name: "Simon Willison's Weblog", type: "blog", description: "Daily practical notes on LLMs, tools, and prompt injection. Over 575 posts tagged 'llm'", audience: "Developers and engineers", frequency: "Daily", url: "https://simonwillison.net", subscriberCount: null, host: "Simon Willison", bestFor: "Real-world LLM usage, tool evaluation, and security considerations", isHighSignal: true },
  { name: "Lilian Weng's Blog", type: "blog", description: "Deep technical explainers on agents, RLHF, diffusion models from an OpenAI researcher", audience: "Researchers and advanced practitioners", frequency: "Monthly", url: "https://lilianweng.github.io", subscriberCount: null, host: "Lilian Weng", bestFor: "Graduate-level depth on core AI concepts — worth reading multiple times", isHighSignal: true },
  { name: "OpenAI Blog", type: "blog", description: "Official blog covering model releases, safety research, and API updates", audience: "Developers and researchers", frequency: "Weekly", url: "https://openai.com/blog", subscriberCount: null, host: null, bestFor: "Official model releases and safety research from the most influential AI lab", isHighSignal: true },
  { name: "Lex Fridman Podcast", type: "podcast", description: "Long-form conversations on AI, science, and philosophy with the world's most influential thinkers", audience: "Broad technical and general audience", frequency: "Weekly", url: "https://lexfridman.com/podcast", subscriberCount: "4.9M YouTube", host: "Lex Fridman", bestFor: "Deep, unhurried conversations with AI's most important figures — Sam Altman, Karpathy, Musk", isHighSignal: true },
  { name: "Dwarkesh Podcast", type: "podcast", description: "Dense, research-backed interviews with frontier AI figures and economists", audience: "Technically sophisticated readers", frequency: "Monthly", url: "https://www.dwarkeshpatel.com", subscriberCount: "300K+", host: "Dwarkesh Patel", bestFor: "The deepest conversations in AI — views that don't appear in press releases", isHighSignal: true },
  { name: "Latent Space Podcast", type: "podcast", description: "Weekly AI engineering show for builders — technical depth on what's being built", audience: "AI engineers and builders", frequency: "Weekly", url: "https://latent.space", subscriberCount: "176K+", host: "swyx & Alessio", bestFor: "What AI engineers are actually building and shipping", isHighSignal: true },
  { name: "Hard Fork", type: "podcast", description: "NYT tech reporters breaking down AI and tech news for a mixed audience", audience: "General tech-savvy audience", frequency: "Weekly", url: "https://www.nytimes.com/column/hard-fork", subscriberCount: null, host: "Kevin Roose & Casey Newton", bestFor: "Accessible AI news context — excellent for non-technical community members", isHighSignal: false },
  { name: "No Priors", type: "podcast", description: "AI investing and company-building conversations with top VCs and lab founders", audience: "Founders and investors", frequency: "Weekly", url: "https://www.nopriorspod.com", subscriberCount: null, host: "Sarah Guo & Elad Gil", bestFor: "AI investing landscape and company-building strategy from top VCs", isHighSignal: false },
  { name: "Matt Wolfe (Future Tools)", type: "youtube", description: "Best general-audience AI news breakdowns and tool reviews. Highly accessible.", audience: "General audience", frequency: "Multiple per week", url: "https://youtube.com/@mreflow", subscriberCount: "810K+", host: "Matt Wolfe", bestFor: "Accessible AI tool reviews and news — best starting point for non-technical followers", isHighSignal: false },
  { name: "Two Minute Papers", type: "youtube", description: "Academic AI research summarized in short, engaging videos", audience: "Research-curious audience", frequency: "Weekly", url: "https://youtube.com/@TwoMinutePapers", subscriberCount: "1.74M+", host: "Karoly Zsolnai-Fehér", bestFor: "Stay current on AI research papers without reading them yourself", isHighSignal: false },
  { name: "3Blue1Brown", type: "youtube", description: "Visually stunning animated explainers on neural networks, linear algebra, and deep learning intuition. Grant Sanderson's videos on backpropagation and transformers are the clearest explanations on the internet.", audience: "Beginners and intermediate learners", frequency: "Monthly", url: "https://youtube.com/@3blue1brown", subscriberCount: "7M+", host: "Grant Sanderson", bestFor: "Build rock-solid visual intuition for how neural networks, transformers, and backpropagation actually work — the essential foundation for understanding AI", isHighSignal: true },
  { name: "Techmeme", type: "news_site", description: "Real-time tech news aggregator — updated continuously, best tech news hub overall", audience: "All tech professionals", frequency: "Real-time", url: "https://techmeme.com", subscriberCount: null, host: null, bestFor: "Best overall tech news aggregator — everything important surfaces here", isHighSignal: true },
  { name: "VentureBeat AI", type: "news_site", description: "Product launches, funding rounds, and enterprise AI adoption coverage", audience: "Enterprise tech leaders", frequency: "Daily", url: "https://venturebeat.com/ai", subscriberCount: null, host: null, bestFor: "Enterprise AI adoption, product launches, and funding news", isHighSignal: false },
  { name: "Google Research Blog", type: "blog", description: "Official research blog from Google — covering AI breakthroughs, new architectures, and applied ML across Google's product lines", audience: "Researchers and technical practitioners", frequency: "Weekly", url: "https://research.google/blog", subscriberCount: null, host: null, bestFor: "Primary source for Google's own AI research — papers, models, and tools before they appear anywhere else", isHighSignal: true },
  { name: "Meta AI Blog", type: "blog", description: "Official AI research blog from Meta — covering LLaMA, Llama models, multimodal AI, and open-source ML infrastructure", audience: "Researchers and developers", frequency: "Weekly", url: "https://ai.meta.com/blog", subscriberCount: null, host: null, bestFor: "Open-source AI research from Meta — LLaMA model releases, PyTorch updates, and foundational research", isHighSignal: true },
  { name: "AWS Machine Learning Blog", type: "blog", description: "Practical guides, case studies, and announcements from AWS on deploying ML in production", audience: "Cloud architects and ML engineers", frequency: "Multiple per week", url: "https://aws.amazon.com/blogs/machine-learning", subscriberCount: null, host: null, bestFor: "Real-world ML deployment on AWS — SageMaker, Bedrock, and enterprise AI infrastructure", isHighSignal: false },
  { name: "MIRI Blog", type: "blog", description: "Machine Intelligence Research Institute — technical posts on AI alignment, decision theory, and existential risk from misaligned AI", audience: "AI safety researchers and technical thinkers", frequency: "Occasional", url: "https://intelligence.org/blog", subscriberCount: null, host: null, bestFor: "Deep technical AI alignment research — essential reading if you take long-term AI risk seriously", isHighSignal: false },
  { name: "O'Reilly AI & ML", type: "blog", description: "Practical AI/ML content from O'Reilly — tutorials, reports, and industry analysis on applied machine learning", audience: "Practitioners and enterprise adopters", frequency: "Weekly", url: "https://www.oreilly.com/radar/topics/ai-ml", subscriberCount: null, host: null, bestFor: "Practical ML engineering and enterprise AI adoption — less hype, more working code", isHighSignal: false },
  { name: "The Verge - AI", type: "news_site", description: "AI coverage from one of tech journalism's most respected outlets — consumer impact, product launches, and policy debates", audience: "Tech-savvy general audience", frequency: "Daily", url: "https://www.theverge.com/ai-artificial-intelligence", subscriberCount: null, host: null, bestFor: "Accessible, well-written AI news with cultural and consumer context — great for non-specialists", isHighSignal: false },
  { name: "WIRED - AI", type: "news_site", description: "In-depth AI reporting from WIRED — investigative journalism, long-form features, and policy implications", audience: "Educated general audience", frequency: "Daily", url: "https://www.wired.com/tag/artificial-intelligence", subscriberCount: null, host: null, bestFor: "Investigative AI journalism with cultural depth — where technology meets politics, ethics, and society", isHighSignal: true },
  { name: "TechCrunch - AI", type: "news_site", description: "Startup-focused AI coverage — funding rounds, product launches, and founder interviews in the AI ecosystem", audience: "Founders, investors, and operators", frequency: "Daily", url: "https://techcrunch.com/category/artificial-intelligence", subscriberCount: null, host: null, bestFor: "AI startup ecosystem news — who's raising, who's shipping, and who the VCs are betting on", isHighSignal: false },
  { name: "The Guardian - AI", type: "news_site", description: "Long-form AI journalism from The Guardian — policy, ethics, labor impacts, and societal consequences of AI", audience: "Policy-minded and general readers", frequency: "Daily", url: "https://www.theguardian.com/technology/artificialintelligenceai", subscriberCount: null, host: null, bestFor: "AI ethics, policy, and societal impact — perspectives often missing from tech-first outlets", isHighSignal: false },
  { name: "Ars Technica - AI", type: "news_site", description: "Deep technical AI reporting from Ars Technica — rigorous, skeptical, and peer-review-adjacent", audience: "Technical readers and scientists", frequency: "Daily", url: "https://arstechnica.com/ai", subscriberCount: null, host: null, bestFor: "High-quality skeptical tech journalism — Ars applies scientific rigor to AI claims and hype", isHighSignal: true },
  { name: "KDnuggets", type: "news_site", description: "One of the oldest AI/ML communities — tutorials, job postings, datasets, tool reviews, and research summaries", audience: "Data scientists and ML practitioners", frequency: "Daily", url: "https://www.kdnuggets.com", subscriberCount: null, host: null, bestFor: "Practical data science and ML learning resources — tutorials, polls, and the job board that launched careers", isHighSignal: false },
  { name: "Hacker News - AI", type: "news_site", description: "Y Combinator's community news board — AI papers, tools, and debates surface here first, with technical commentary from engineers and founders", audience: "Developers, founders, and researchers", frequency: "Real-time", url: "https://news.ycombinator.com", subscriberCount: null, host: null, bestFor: "First look at new AI tools, papers, and debates — technical community reaction often predicts what goes mainstream", isHighSignal: true },
  { name: "One Useful Thing", type: "newsletter", description: "Ethan Mollick's rigorous, experiment-backed essays on how AI is changing knowledge work, education, and creativity. One of the most widely shared AI reads among non-technical professionals.", audience: "Knowledge workers, educators, managers", frequency: "Weekly", url: "https://www.oneusefulthing.org", subscriberCount: "400K+", host: "Ethan Mollick", bestFor: "How AI changes real work — backed by experiments, not hype; essential for anyone applying AI in professional settings", isHighSignal: true },
  { name: "Prompt Capital", type: "newsletter", description: "India-focused AI newsletter decoding global AI trends, policy, and investments — including Budget AI analysis, Google's century bonds, and frontier model developments.", audience: "Indian tech professionals and investors", frequency: "Weekly", url: "https://promptcapital.substack.com", subscriberCount: null, host: "Rohit Singh", bestFor: "India-angle AI coverage — policy, investment, and global AI developments translated for the Indian context", isHighSignal: false },
  { name: "Dario Amodei's Essays", type: "blog", description: "Long-form essays from Anthropic's CEO on the philosophy and future of AI. 'Machines of Loving Grace' and 'The Adolescence of Technology' are essential reads for anyone tracking AGI timelines.", audience: "Researchers, founders, policy thinkers", frequency: "Occasional", url: "https://darioamodei.com", subscriberCount: null, host: "Dario Amodei", bestFor: "The most rigorous long-form thinking on what powerful AI means for humanity — primary source for Anthropic's worldview", isHighSignal: true },
  { name: "The Neuron", type: "newsletter", description: "Witty, Morning Brew-style daily AI newsletter covering industry shifts and major model releases in under five minutes. Sharp, punchy, and highly readable.", audience: "Business professionals and general tech audience", frequency: "Daily", url: "https://www.theneurondaily.com", subscriberCount: "500K+", host: null, bestFor: "Fast, engaging daily AI briefing with personality — best for busy professionals who want signal without the dry technical jargon", isHighSignal: true },
  { name: "AlphaSignal", type: "newsletter", description: "Weekly newsletter using its own AI algorithms to surface the most significant research papers and technical breakthroughs trending in the R&D community.", audience: "AI researchers and advanced practitioners", frequency: "Weekly", url: "https://alphasignal.ai", subscriberCount: "200K+", host: null, bestFor: "AI-curated research discovery — find the papers that matter before they become mainstream, without reading arXiv yourself", isHighSignal: true },
];

const communities = [
  { name: "r/ChatGPT", platform: "reddit", memberCount: "9.9M+", description: "Broad ChatGPT news, prompting tips, and community reactions", url: "https://reddit.com/r/ChatGPT", bestFor: "General ChatGPT news and community prompting tips" },
  { name: "r/OpenAI", platform: "reddit", memberCount: "2.3M+", description: "OpenAI model updates and developer discussions", url: "https://reddit.com/r/OpenAI", bestFor: "OpenAI model updates and API discussions" },
  { name: "r/Artificial", platform: "reddit", memberCount: "1.1M+", description: "General AI news and debates across all labs and research areas", url: "https://reddit.com/r/Artificial", bestFor: "Broad AI news and cross-lab discussions" },
  { name: "r/LocalLLaMA", platform: "reddit", memberCount: "500K+", description: "Open-source and self-hosted LLM community — fine-tuning, quantization, deployment", url: "https://reddit.com/r/LocalLLaMA", bestFor: "Running LLMs locally, open-source models, fine-tuning" },
  { name: "OpenAI Discord", platform: "discord", memberCount: "100K+", description: "Developer discussions, API help, and feature previews", url: "https://discord.gg/openai", bestFor: "Developer API help and early access to OpenAI features" },
  { name: "Hugging Face Discord", platform: "discord", memberCount: "50K+", description: "Open-source ML, NLP, and dataset sharing community", url: "https://discord.gg/huggingface", bestFor: "Open-source model sharing, dataset collaboration, ML research" },
  { name: "Learn AI Together", platform: "discord", memberCount: "30K+", description: "Community-driven learning with weekly reading groups and job postings", url: "https://discord.gg/learnaitogether", bestFor: "Structured AI learning, reading groups, and job hunting" },
  { name: "Latent Space Discord", platform: "discord", memberCount: "20K+", description: "AI engineering community for builders, linked to the Latent Space podcast", url: "https://discord.gg/latentspace", bestFor: "AI engineering discussions for serious builders" },
  { name: "CC For Everyone", platform: "community", memberCount: null, description: "Community dedicated to making Claude Code accessible to all — tutorials, tips, and resources for non-engineers using AI coding tools", url: "https://ccforeveryone.com", bestFor: "Getting started with Claude Code and AI-assisted development as a non-technical user" },
  { name: "r/MachineLearning", platform: "reddit", memberCount: "2.9M+", description: "Official Reddit home for ML research — paper discussions, career advice, and state-of-the-art model releases. Higher technical bar than r/Artificial.", url: "https://reddit.com/r/MachineLearning", bestFor: "ML research discussions, paper breakdowns, and career growth for serious practitioners" },
];

export async function seedIfEmpty() {
  const existing = await db.select().from(peopleTable).limit(1);
  if (existing.length > 0) return;

  logger.info("Database is empty — running seed...");

  await db.insert(peopleTable).values(people);
  await db.insert(sourcesTable).values(sources);
  await db.insert(communitiesTable).values(communities);

  logger.info({ people: people.length, sources: sources.length, communities: communities.length }, "Seed complete");
}

export async function updateSeedData() {
  const existingPeople = await db.select({ id: peopleTable.id, name: peopleTable.name, imageUrl: peopleTable.imageUrl }).from(peopleTable);
  const existingNames = new Set(existingPeople.map((p) => p.name));
  const newPeople = people.filter((p) => !existingNames.has(p.name));
  if (newPeople.length > 0) {
    await db.insert(peopleTable).values(newPeople);
    logger.info({ count: newPeople.length, names: newPeople.map((p) => p.name) }, "Added new people");
  }

  // Patch imageUrl for existing people whose URL is missing or uses old /twitter/ path
  const seedByName = Object.fromEntries(people.map((p) => [p.name, p]));
  const toUpdate = existingPeople.filter((p) => {
    const seed = seedByName[p.name];
    if (!seed?.imageUrl) return false;
    return !p.imageUrl || p.imageUrl.includes("/twitter/");
  });
  for (const p of toUpdate) {
    const seed = seedByName[p.name]!;
    await db.update(peopleTable).set({ imageUrl: seed.imageUrl }).where(eq(peopleTable.id, p.id));
  }
  if (toUpdate.length > 0) {
    logger.info({ count: toUpdate.length, names: toUpdate.map((p) => p.name) }, "Patched imageUrl for existing people");
  }

  const existingSources = await db.select({ name: sourcesTable.name }).from(sourcesTable);
  const existingSourceNames = new Set(existingSources.map((s) => s.name));
  const newSources = sources.filter((s) => !existingSourceNames.has(s.name));
  if (newSources.length > 0) {
    await db.insert(sourcesTable).values(newSources);
    logger.info({ count: newSources.length, names: newSources.map((s) => s.name) }, "Added new sources");
  }

  const existingCommunities = await db.select({ name: communitiesTable.name }).from(communitiesTable);
  const existingCommunityNames = new Set(existingCommunities.map((c) => c.name));
  const newCommunities = communities.filter((c) => !existingCommunityNames.has(c.name));
  if (newCommunities.length > 0) {
    await db.insert(communitiesTable).values(newCommunities);
    logger.info({ count: newCommunities.length, names: newCommunities.map((c) => c.name) }, "Added new communities");
  }
}
